version: '3'

services: 
  ipsec:
    image: hwdsl2/ipsec-vpn-server
    restart: always
    network_mode: "host"
    env_file: ./ipsec/vpn.env
    privileged: true

  xui:
    image: enwaiax/x-ui
    restart: always
    privileged: true
    network_mode: "host"    
    volumes:
      - ./x-ui/db/:/etc/x-ui/
      - ./x-ui/cert/:/root/cert/
